# 服务端口
server:
  port: 8004

spring:
  application:
    # 服务名
    name: service-cms
  # mysql 数据库连接配置
  datasource:
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 地址
    url: jdbc:mysql://www.edu.com/yuunik?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    # 用户名
    username: root
    # 密码
    password: Chow.1997
  # 返回 json 的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone: GMT+8
  # nacos 服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  # 配置 mapper xml 文件的路径
  mapper-locations: classpath:com/yuunik/cmsservice/mapper/xml/*.xml
  # mybatis 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl