# 服务端口
server:
  port: 8001
# 服务名
spring:
  application:
    name: service-edu
  # 环境设置: dev, test, prod
  profiles:
    active: dev
  # mysql 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuunik?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # json
  jackson:
    # 返回 json 的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 日志输出相关配置
# mybatis
# mybatis-plus:
  # configuration:
    # 输出日志
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 设置日志级别
# logging:
  # level:
    # root: INFO
