# 服务端口
server:
  port: 8001
# 服务名
spring:
  application:
    name: service-edu
  # 环境设置: dev, test, prod
  profiles:
    active: dev
  # mysql 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.edu.com:3306/yuunik?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Chow.1997
  # json
  jackson:
    # 返回 json 的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos 服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # redis 配置
  redis:
    # 地址
    host: www.edu.com
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 连接池配置
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 20
        # 连接池最大阻塞时间（负数表示没限制）
        max-wait: -1
        # 连接池最大空闲连接数
        max-idle: 5
        # 连接池最小空闲连接数
        min-idle: 0
# 日志输出相关配置
# mybatis
mybatis-plus:
  configuration:
    # 输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper xml文件的路径
  mapper-locations: classpath:com/yuunik/eduservice/mapper/xml/*.xml
# 设置日志级别
#  logging:
#    level:
#      root: INFO

# 开启熔断器机制
feign:
  hystrix:
    enabled: true

# 设置 hystrix 超时时间, 默认为 1000 ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
