# 端口号
server:
  port: 8003

spring:
  application:
    # 服务名
    name: service-vod
  servlet:
    # 文件上传配置
    multipart:
      # 单个文件大小
      max-file-size: 1024MB
      # 总大小
      max-request-size: 1024MB
