server:
  # 服务端口
  port: 8006

spring:
  application:
    # 服务名
    name: service-order
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.edu.com:3306/yuunik?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Chow.1997
  # 返回 json 的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos 相关配置
  cloud:
    nacos:
      discovery:
        # 服务地址
        server-addr: 127.0.0.1:8848

# 开启熔断机制
feign:
  hystrix:
    enabled: true

# 设置 hystrix 超时时间, 默认为 1000 ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

# mybatis
mybatis-plus:
  # 配置 mapper xml 文件所在的路径
  mapper-locations: classpath:com/yuunik/ordreservice/mapper/xml/*.xml
  configuration:
    # mybatis 输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 微信支付配置
wechat:
  pay:
    #关联的公众号appid
    app-id: wx74862e0dfcf69954
    #商户号
    partner-id: 1558950191
    #商户key
    partner-key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    #回调地址
    notify-url: http://guli.shop/api/order/weixinPay/weixinNotify
    # 微信支付二维码请求路径
    domain: https://api.mch.weixin.qq.com/pay/unifiedorder
    # 微信支付状态查询路径
    query-order-domain: https://api.mch.weixin.qq.com/pay/orderquery
