server:
  # 服务端口号
  port: 8888

spring:
  application:
    # 服务名
    name: canal-educlient

  # 环境设置: dev、test、prod
  profiles:
    active: dev

  # mysql 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuunik?serverTimezone=GMT%2B8
    username: root
    password: root