server:
  # 服务端口号
  port: 8002
  tomcat:
    # 请求最大值
    max-swallow-size: 100MB

spring:
  application:
    # 服务名
    name: service-oss
  profiles:
    # 环境设置: dev, test, prod
    active: dev
  servlet:
    # 文件上传配置
    multipart:
      # 单个文件最大值
      max-file-size: 10MB
      # 总请求最大值
      max-request-size: 10MB
  # nacos 服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 阿里云 oss 配置
aliyun:
  oss:
    file:
      # 地域节点
      endpoint: oss-cn-beijing.aliyuncs.com
      # 访问密钥id
      access-key-id: LTAI5tBgjLQ7v7eX9vhLdaYR
      # 访问密钥
      access-key-secret: WbC7aXsRYMGnr02Z3gQiRPWubo1PCU
      # bucket 名称
      bucket-name: edu-yuunik
