# 服务端口
server:
  port: 8007

spring:
  application:
    # 服务名
    name: service-statistics
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.edu.com:3306/yuunik?serverTimezone=GMT%2B8
    username: root
    password: Chow.1997
  # 返回 json 的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  # 配置 mapper xml 文件的路径
  mapper-locations: classpath:com/yuunik/statistics/mapper/*.xml
  # mybatis 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 开启熔断器机制
feign:
  hystrix:
    enabled: true

# 设置 hystrix 的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000